In [1]:
#cargamos librerias
import pandas as pd

In [2]:
#cargamos dataset
homicidios_hechos = pd.read_excel('../dataset/homicidios.xlsx',sheet_name='HECHOS')

In [3]:
homicidios_hechos.head(3)

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO

decidimos que columnas vamos a escoger para obtener la informacion necesaria =
ID, FECHA, LUGAR_DEL_HECHO, DIRECCION NORMALIZADA, COMUNA, pos x, pos y, VICTIMA, ACUSADO

In [4]:
homicidios_hechos.shape

(696, 21)

In [5]:
homicidios_hechos2= homicidios_hechos[['ID', 'FECHA', 'AAAA','MM','DD','HH','LUGAR_DEL_HECHO', 'COMUNA', 'pos x', 'pos y', 'VICTIMA', 'ACUSADO','N_VICTIMAS']]

homicidios_hechos2

,ID,FECHA,AAAA,MM,DD,HH,LUGAR_DEL_HECHO,COMUNA,pos x,pos y,VICTIMA,ACUSADO,N_VICTIMAS
0,2016-0001,2016-01-01,2016,1,1,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,8,-58.47533969,-34.68757022,MOTO,AUTO,1
1,2016-0002,2016-01-02,2016,1,2,1,AV GRAL PAZ Y AV DE LOS CORRALES,9,-58.50877521,-34.66977709,AUTO,PASAJEROS,1
2,2016-0003,2016-01-03,2016,1,3,7,AV ENTRE RIOS 2034,1,-58.39040293,-34.63189362,MOTO,AUTO,1
3,2016-0004,2016-01-10,2016,1,10,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,8,-58.46503904,-34.68092974,MOTO,SD,1
4,2016-0005,2016-01-21,2016,1,21,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,2021-12-13,2021,12,13,17,AV. RIESTRA Y MOM,7,-58.43353773,-34.64561636,MOTO,AUTO,1
692,2021-0094,2021-12-20,2021,12,20,1,AU DELLEPIANE Y LACARRA,9,-58.46739825,-34.65117757,MOTO,AUTO,1
693,2021-0095,2021-12-30,2021,12,30,0,AV. GAONA Y TERRADA,11,-58.47293407,-34.61984745,MOTO,CARGAS,1
694,2021-0096,2021-12-15,2021,12,15,10,AV. EVA PERON 4071,9,-58.47066794,-34.65021673,AUTO,CARGAS,1
695,2021-0097,2021-11-18,2021,11,18,6,PADRE CARLOS MUJICA 709,1,-58.37976155,-34.58679619,BICICLETA,AUTO,1

In [6]:
# Identificar valores nulos
valores_nulos = homicidios_hechos2.isnull()
valores_nulos

,ID,FECHA,AAAA,MM,DD,HH,LUGAR_DEL_HECHO,COMUNA,pos x,pos y,VICTIMA,ACUSADO,N_VICTIMAS
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,False,False,False,False,False,False,False,False,False,False,False,False,False
692,False,False,False,False,False,False,False,False,False,False,False,False,False
693,False,False,False,False,False,False,False,False,False,False,False,False,False
694,False,False,False,False,False,False,False,False,False,False,False,False,False
695,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
homicidios_hechos2.dtypes

ID                         object
FECHA              datetime64[ns]
AAAA                        int64
MM                          int64
DD                          int64
HH                         object
LUGAR_DEL_HECHO            object
COMUNA                      int64
pos x                      object
pos y                      object
VICTIMA                    object
ACUSADO                    object
N_VICTIMAS                  int64
dtype: object

In [8]:
#guardar el nuevo archivio previamente filtrado
homicidios_hechos2.to_csv('../dataset/homicidios_hechos.csv')